### ISSUE TITLE
Headers might not be added

### ISSUE THREAD

**Issue by posener** [mitchellh/go-server-timing#10]
In go, if a handler doesn't call `WriteHeader`, the response is still valid, and will be 200.
If the `next` handler wrapped in middleware does not call this function, the timing headers won't be in the response.

I'm not sure this is an issue, but it can be fixed and save people time trying to figure out why the headers were not added.

**Comment by mitchellh** [comment]
Good catch! Definitely worth fixing and should be easy since we can just detect if WriteHeader was called or not (as you pointed out).
