### ISSUE TITLE
Headers still may not be written

### ISSUE THREAD

**Issue by bendoerr** [mitchellh/go-server-timing#14]
Hello, thanks for this. Your fix for #10 wasn't complete. After you have written to the response you can no longer add headers. To fix this you'll need to catch `Write` with `httpsnoop`. For example the following works well for me.

```go
			Write: func(original httpsnoop.WriteFunc) httpsnoop.WriteFunc {
				return func(b []byte) (int, error) {
					// Write the headers
					writeHeader(headers, &h)

					// Remember that headers were written
					headerWritten = true

					// Call the original Write function
					return original(b)
				}
			},
```

**Comment by mitchellh** [comment]
Can you please share with me a case where this happens?

The `net/http.ResponseWriter` docs state that any call to `Write` must call `WriteHeader` if it hasn't been called before: https://golang.org/pkg/net/http/#ResponseWriter So the scenario you describe sounds to me like a poorly behaved `net/http.ResponseWriter` implementation potentially.

But if you can show me some sample code that triggers it I can add a test case and get a fix in.

**Comment by bendoerr** [comment]
So `net/http.ResponseWriter.Write([]byte) (int, error)` says 

> If WriteHeader has not yet been called, Write calls WriteHeader(http.StatusOK) before writing the data.

Which means that it's going to call it's own `WriteHeader` not the snooped one. It's super easy to test. Take the example code and comment out the line to WriteHeader https://github.com/mitchellh/go-server-timing/blob/master/example/main.go#L65.

**Comment by mitchellh** [comment]
Cool this makes a ton of sense thank you. I'll try to whip up a test case soon and get a fix in.

**Comment by mitchellh** [comment]
Got a fix in: https://github.com/mitchellh/go-server-timing/pull/16

Funny thing is that we had a test for this already, but `net/http/httptest.ResponseRecorder` will allow you to set headers anytime! So I had to add another test that uses a "real" HTTP round trip to verify.
