### ISSUE TITLE
more realistic example wanted

### ISSUE THREAD

**Issue by ensonic** [mitchellh/go-server-timing#20]
In practise people will often have more that one handler, e.g.
```go
    http.HandleFunc("/path1", path1Handler)
    http.HandleFunc("/path2", path2Handler)
    http.Handle("/metrics", promhttp.Handler())
	
    http.ListenAndServe(":80", nil)
```
if tried to change the last line to:
```go
    h := servertiming.Middleware(http.DefaultServeMux, nil)
    http.ListenAndServe(":80", h)
```
but get not "Server-Timing" headers.

**Comment by mitchellh** [comment]
On the surface, this should work fine. More information or investigation is required here. I’m not at a computer (I’m on mobile atm) for another week but if anyone wants to jump in and give this a shot I’d appreciate it. 

Are you setting any metrics? Because if you don’t set any server timing metrics then the header is omitted.

**Comment by ensonic** [comment]
Thanks for the quick reply. I am changing this code:
https://github.com/googlecloudrobotics/core/blob/master/src/go/cmd/http-relay-server/main.go#L231
and here is the relevant change:
https://gist.github.com/ensonic/d4dcaf49bc5616315997feeb8cca8c14

In the installation the access goes through an nginx ingress. I'll try to figure if this is stripping headers.

**Comment by ensonic** [comment]
Doh. Everything is good. I was running th wrong image :/  So this works:
```go
h := servertiming.Middleware(http.DefaultServeMux, nil)
http.ListenAndServe(":80", h)
```
works. Do you want a PR for the docs/example?

**Comment by mitchellh** [comment]
No, I think or would hope this makes sense to someone with Go experience (beginner or otherwise). Middlewares warp any handler. Glad to know it works!
